from PyQt5.QtWidgets import QLabel, QWidget, QPushButton, QGridLayout, QComboBox, QFileDialog, QLineEdit, QDialog, QVBoxLayout, QHBoxLayout
from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication, Qt
from PyQt5.QtGui import QFont, QPixmap
from ExcelWriter import ExcelWriter
from VisualElement import VisualTable
from xlutils.copy import copy
from xlutils.styles import Styles
import xlrd
import datetime

class MainIntroWindow(QDialog):
    def __init__(self):
        super().__init__()
        self.original_filename = ''
        self.new_save_filename = ''

        # Day of week to set default day of week combo box.
        self.day_of_week = datetime.datetime.today().weekday()

        ####################### Defaults used for testing #####################################
        self.default_open_path = "Choose Schedule(.xls file) To Edit"
        self.default_save_path = "Create Filled Out Schedule Location"
        self.open_file_found = False
        self.save_file_found = False
        self.day_index = 0

        # Default CE counts for each hour. Can possibly have one for each day.
        self.recommended_ce = [6, 9, 10, 11, 11, 11, 10, 11, 12, 13, 13, 11, 9]
        self.setupUi(self)
        #self.setStyleSheet("background-color: rgba(204, 0, 0, 4)")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 454)
        self.widget = QWidget(MainWindow)
        self.widget.setGeometry(QRect(10, 20, 581, 78))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.open_file_button = QPushButton(self.widget)
        self.open_file_button.setObjectName("open_file_button")
        self.open_file_button.clicked.connect(self.handleOpenFileButtonClick)
        self.open_file_button.setFocusPolicy(Qt.NoFocus)
        self.horizontalLayout_3.addWidget(self.open_file_button)
        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.set_save_file_button = QPushButton(self.widget)
        self.set_save_file_button.setObjectName("set_save_file_button")
        self.set_save_file_button.clicked.connect(self.handleSaveFileButtonClick)
        self.set_save_file_button.setFocusPolicy(Qt.NoFocus)
        self.horizontalLayout_4.addWidget(self.set_save_file_button)
        self.lineEdit_2 = QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.run_program_button = QPushButton(MainWindow)
        self.run_program_button.setGeometry(QRect(230, 400, 141, 32))
        self.run_program_button.setObjectName("run_program_button")
        self.run_program_button.clicked.connect(self.runProgram)
        self.run_program_button.setDisabled(True)
        self.run_program_button.setFocusPolicy(Qt.NoFocus)
        self.widget1 = QWidget(MainWindow)
        self.widget1.setGeometry(QRect(200, 110, 210, 26))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_15 = QLabel(self.widget1)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.day_selector = QComboBox(self.widget1)
        self.day_selector.setObjectName("day_selector")
        self.day_selector.addItem("")
        self.day_selector.addItem("")
        self.day_selector.addItem("")
        self.day_selector.addItem("")
        self.day_selector.addItem("")
        self.day_selector.addItem("")
        self.day_selector.addItem("")

        if self.day_of_week < 6:
            self.day_selector.setCurrentIndex(self.day_of_week+1)
        else:
            self.day_selector.setCurrentIndex(0)

        self.horizontalLayout_5.addWidget(self.day_selector)
        self.widget2 = QWidget(MainWindow)
        self.widget2.setGeometry(QRect(125, 150, 340, 242))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_6 = QVBoxLayout(self.widget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QLabel(self.widget2)
        font = QFont()
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QLabel(self.widget2)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QLabel(self.widget2)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QLabel(self.widget2)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QLabel(self.widget2)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QLabel(self.widget2)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QLabel(self.widget2)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QLabel(self.widget2)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.eight_am_ce_count = QComboBox(self.widget2)
        self.eight_am_ce_count.setEditable(False)
        self.eight_am_ce_count.setObjectName("comboBox_2")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.addItem("")
        self.eight_am_ce_count.setCurrentIndex(self.recommended_ce[0])
        self.verticalLayout.addWidget(self.eight_am_ce_count)
        self.nine_am_ce_count = QComboBox(self.widget2)
        self.nine_am_ce_count.setEditable(False)
        self.nine_am_ce_count.setObjectName("comboBox_6")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.addItem("")
        self.nine_am_ce_count.setCurrentIndex(self.recommended_ce[1])
        self.verticalLayout.addWidget(self.nine_am_ce_count)
        self.ten_am_ce_count = QComboBox(self.widget2)
        self.ten_am_ce_count.setEditable(False)
        self.ten_am_ce_count.setObjectName("comboBox_4")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.addItem("")
        self.ten_am_ce_count.setCurrentIndex(self.recommended_ce[2])
        self.verticalLayout.addWidget(self.ten_am_ce_count)
        self.eleven_am_ce_count = QComboBox(self.widget2)
        self.eleven_am_ce_count.setEditable(False)
        self.eleven_am_ce_count.setObjectName("comboBox_7")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.addItem("")
        self.eleven_am_ce_count.setCurrentIndex(self.recommended_ce[3])
        self.verticalLayout.addWidget(self.eleven_am_ce_count)
        self.twelve_pm_ce_count = QComboBox(self.widget2)
        self.twelve_pm_ce_count.setEditable(False)
        self.twelve_pm_ce_count.setObjectName("comboBox_3")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.addItem("")
        self.twelve_pm_ce_count.setCurrentIndex(self.recommended_ce[4])
        self.verticalLayout.addWidget(self.twelve_pm_ce_count)
        self.one_pm_ce_count = QComboBox(self.widget2)
        self.one_pm_ce_count.setEditable(False)
        self.one_pm_ce_count.setObjectName("comboBox_5")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.addItem("")
        self.one_pm_ce_count.setCurrentIndex(self.recommended_ce[5])
        self.verticalLayout.addWidget(self.one_pm_ce_count)
        self.two_pm_ce_count = QComboBox(self.widget2)
        self.two_pm_ce_count.setEditable(False)
        self.two_pm_ce_count.setObjectName("comboBox_8")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.addItem("")
        self.two_pm_ce_count.setCurrentIndex(self.recommended_ce[6])
        self.verticalLayout.addWidget(self.two_pm_ce_count)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QLabel(self.widget2)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QLabel(self.widget2)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QLabel(self.widget2)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_14 = QLabel(self.widget2)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_13 = QLabel(self.widget2)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_12 = QLabel(self.widget2)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.three_pm_ce_count = QComboBox(self.widget2)
        self.three_pm_ce_count.setEditable(False)
        self.three_pm_ce_count.setObjectName("comboBox")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.addItem("")
        self.three_pm_ce_count.setCurrentIndex(self.recommended_ce[7])
        self.verticalLayout_4.addWidget(self.three_pm_ce_count)
        self.four_pm_ce_count = QComboBox(self.widget2)
        self.four_pm_ce_count.setEditable(False)
        self.four_pm_ce_count.setObjectName("comboBox_11")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.addItem("")
        self.four_pm_ce_count.setCurrentIndex(self.recommended_ce[8])
        self.verticalLayout_4.addWidget(self.four_pm_ce_count)
        self.five_pm_ce_count = QComboBox(self.widget2)
        self.five_pm_ce_count.setEditable(False)
        self.five_pm_ce_count.setObjectName("comboBox_10")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.addItem("")
        self.five_pm_ce_count.setCurrentIndex(self.recommended_ce[9])
        self.verticalLayout_4.addWidget(self.five_pm_ce_count)
        self.six_pm_ce_count = QComboBox(self.widget2)
        self.six_pm_ce_count.setEditable(False)
        self.six_pm_ce_count.setObjectName("comboBox_12")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.addItem("")
        self.six_pm_ce_count.setCurrentIndex(self.recommended_ce[10])
        self.verticalLayout_4.addWidget(self.six_pm_ce_count)
        self.seven_pm_ce_count = QComboBox(self.widget2)
        self.seven_pm_ce_count.setEditable(False)
        self.seven_pm_ce_count.setObjectName("comboBox_9")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.addItem("")
        self.seven_pm_ce_count.setCurrentIndex(self.recommended_ce[11])
        self.verticalLayout_4.addWidget(self.seven_pm_ce_count)
        self.eight_pm_ce_count = QComboBox(self.widget2)
        self.eight_pm_ce_count.setEditable(False)
        self.eight_pm_ce_count.setObjectName("comboBox_13")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.addItem("")
        self.eight_pm_ce_count.setCurrentIndex(self.recommended_ce[12])
        self.verticalLayout_4.addWidget(self.eight_pm_ce_count)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label.raise_()
        self.three_pm_ce_count.raise_()
        self.eight_am_ce_count.raise_()
        self.twelve_pm_ce_count.raise_()
        self.ten_am_ce_count.raise_()
        self.one_pm_ce_count.raise_()
        self.nine_am_ce_count.raise_()
        self.eleven_am_ce_count.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.two_pm_ce_count.raise_()
        self.seven_pm_ce_count.raise_()
        self.five_pm_ce_count.raise_()
        self.four_pm_ce_count.raise_()
        self.six_pm_ce_count.raise_()
        self.eight_pm_ce_count.raise_()
        self.open_file_button.raise_()
        self.set_save_file_button.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_15.raise_()
        self.day_selector.raise_()
        self.run_program_button.raise_()

        # Set up default file parameters
        self.original_filename = self.default_open_path
        self.lineEdit.setText(self.original_filename)
        if self.original_filename != self.default_open_path:
            self.open_file_found = True
        self.new_save_filename = self.default_save_path
        self.lineEdit_2.setText(self.new_save_filename)
        if self.new_save_filename != self.default_save_path:
            self.save_file_found = True

        if self.open_file_found and self.save_file_found:
            self.run_program_button.setDisabled(False)
        else:
            self.run_program_button.setDisabled(True)


        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)
        self.show()

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trader\'s Scheduler"))
        self.open_file_button.setText(_translate("MainWindow", "Choose Original Filename"))
        self.set_save_file_button.setText(_translate("MainWindow", "Choose New Filename"))
        self.run_program_button.setText(_translate("MainWindow", "Set Up Schedule"))
        self.label_15.setText(_translate("MainWindow", "Select a Day"))
        self.day_selector.setItemText(0, _translate("MainWindow", "Monday"))
        self.day_selector.setItemText(1, _translate("MainWindow", "Tuesday"))
        self.day_selector.setItemText(2, _translate("MainWindow", "Wednesday"))
        self.day_selector.setItemText(3, _translate("MainWindow", "Thursday"))
        self.day_selector.setItemText(4, _translate("MainWindow", "Friday"))
        self.day_selector.setItemText(5, _translate("MainWindow", "Saturday"))
        self.day_selector.setItemText(6, _translate("MainWindow", "Sunday"))
        self.label_8.setText(_translate("MainWindow", "Required Number of CE Members"))
        self.label.setText(_translate("MainWindow", "8 a.m"))
        self.label_2.setText(_translate("MainWindow", "9 a.m"))
        self.label_3.setText(_translate("MainWindow", "10 a.m"))
        self.label_4.setText(_translate("MainWindow", "11 a.m"))
        self.label_5.setText(_translate("MainWindow", "12 p.m"))
        self.label_7.setText(_translate("MainWindow", "2 p.m"))
        self.label_6.setText(_translate("MainWindow", "1 p.m"))
        self.eight_am_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.eight_am_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.eight_am_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.eight_am_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.eight_am_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.eight_am_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.eight_am_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.eight_am_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.eight_am_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.eight_am_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.eight_am_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.eight_am_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.eight_am_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.eight_am_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.eight_am_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.eight_am_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.eight_am_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.eight_am_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.eight_am_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.eight_am_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.eight_am_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.eight_am_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.nine_am_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.nine_am_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.nine_am_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.nine_am_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.nine_am_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.nine_am_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.nine_am_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.nine_am_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.nine_am_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.nine_am_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.nine_am_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.nine_am_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.nine_am_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.nine_am_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.nine_am_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.nine_am_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.nine_am_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.nine_am_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.nine_am_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.nine_am_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.nine_am_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.nine_am_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.ten_am_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.ten_am_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.ten_am_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.ten_am_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.ten_am_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.ten_am_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.ten_am_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.ten_am_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.ten_am_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.ten_am_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.ten_am_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.ten_am_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.ten_am_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.ten_am_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.ten_am_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.ten_am_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.ten_am_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.ten_am_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.ten_am_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.ten_am_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.ten_am_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.ten_am_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.eleven_am_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.eleven_am_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.eleven_am_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.eleven_am_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.eleven_am_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.eleven_am_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.eleven_am_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.eleven_am_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.eleven_am_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.eleven_am_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.eleven_am_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.eleven_am_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.eleven_am_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.eleven_am_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.eleven_am_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.eleven_am_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.eleven_am_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.eleven_am_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.eleven_am_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.eleven_am_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.eleven_am_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.eleven_am_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.twelve_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.twelve_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.twelve_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.twelve_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.twelve_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.twelve_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.twelve_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.twelve_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.twelve_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.twelve_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.twelve_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.twelve_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.twelve_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.twelve_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.twelve_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.twelve_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.twelve_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.twelve_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.twelve_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.twelve_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.twelve_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.twelve_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.one_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.one_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.one_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.one_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.one_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.one_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.one_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.one_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.one_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.one_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.one_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.one_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.one_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.one_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.one_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.one_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.one_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.one_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.one_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.one_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.one_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.one_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.two_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.two_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.two_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.two_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.two_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.two_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.two_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.two_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.two_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.two_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.two_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.two_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.two_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.two_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.two_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.two_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.two_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.two_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.two_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.two_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.two_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.two_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.label_14.setText(_translate("MainWindow", "6 p.m"))
        self.label_13.setText(_translate("MainWindow", "7 p.m"))
        self.label_11.setText(_translate("MainWindow", "5 p.m"))
        self.label_10.setText(_translate("MainWindow", "4 p.m"))
        self.label_9.setText(_translate("MainWindow", "3 p.m"))
        self.label_12.setText(_translate("MainWindow", "8 p.m"))
        self.three_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.three_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.three_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.three_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.three_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.three_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.three_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.three_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.three_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.three_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.three_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.three_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.three_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.three_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.three_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.three_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.three_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.three_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.three_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.three_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.three_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.three_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.four_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.four_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.four_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.four_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.four_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.four_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.four_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.four_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.four_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.four_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.four_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.four_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.four_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.four_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.four_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.four_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.four_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.four_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.four_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.four_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.four_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.four_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.five_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.five_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.five_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.five_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.five_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.five_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.five_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.five_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.five_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.five_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.five_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.five_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.five_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.five_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.five_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.five_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.five_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.five_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.five_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.five_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.five_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.five_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.six_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.six_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.six_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.six_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.six_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.six_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.six_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.six_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.six_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.six_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.six_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.six_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.six_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.six_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.six_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.six_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.six_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.six_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.six_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.six_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.six_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.six_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.seven_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.seven_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.seven_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.seven_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.seven_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.seven_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.seven_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.seven_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.seven_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.seven_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.seven_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.seven_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.seven_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.seven_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.seven_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.seven_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.seven_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.seven_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.seven_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.seven_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.seven_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.seven_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))
        self.eight_pm_ce_count.setCurrentText(_translate("MainWindow", "0"))
        self.eight_pm_ce_count.setItemText(0, _translate("MainWindow", "0"))
        self.eight_pm_ce_count.setItemText(1, _translate("MainWindow", "1"))
        self.eight_pm_ce_count.setItemText(2, _translate("MainWindow", "2"))
        self.eight_pm_ce_count.setItemText(3, _translate("MainWindow", "3"))
        self.eight_pm_ce_count.setItemText(4, _translate("MainWindow", "4"))
        self.eight_pm_ce_count.setItemText(5, _translate("MainWindow", "5"))
        self.eight_pm_ce_count.setItemText(6, _translate("MainWindow", "6"))
        self.eight_pm_ce_count.setItemText(7, _translate("MainWindow", "7"))
        self.eight_pm_ce_count.setItemText(8, _translate("MainWindow", "8"))
        self.eight_pm_ce_count.setItemText(9, _translate("MainWindow", "9"))
        self.eight_pm_ce_count.setItemText(10, _translate("MainWindow", "10"))
        self.eight_pm_ce_count.setItemText(11, _translate("MainWindow", "11"))
        self.eight_pm_ce_count.setItemText(12, _translate("MainWindow", "12"))
        self.eight_pm_ce_count.setItemText(13, _translate("MainWindow", "13"))
        self.eight_pm_ce_count.setItemText(14, _translate("MainWindow", "14"))
        self.eight_pm_ce_count.setItemText(15, _translate("MainWindow", "15"))
        self.eight_pm_ce_count.setItemText(16, _translate("MainWindow", "16"))
        self.eight_pm_ce_count.setItemText(17, _translate("MainWindow", "17"))
        self.eight_pm_ce_count.setItemText(18, _translate("MainWindow", "18"))
        self.eight_pm_ce_count.setItemText(19, _translate("MainWindow", "19"))
        self.eight_pm_ce_count.setItemText(20, _translate("MainWindow", "20"))


    def temp_setupUi(self, Dialog):
        self.setWindowTitle("Trader's Scheduler")
        Dialog.resize(574, 270)
        self.day_selector = QComboBox(Dialog)
        self.day_selector.setGeometry(QRect(250, 80, 121, 26))
        self.day_selector.setEditable(False)
        self.day_selector.setCurrentText("")
        self.day_selector.setObjectName("day_selector")
        self.day_selector.addItems(["Monday", "Tuesday", "Wednesday", "Thursday",
                                    "Friday", "Saturday", "Sunday", "All"])
        self.label = QLabel(Dialog)
        self.label.setGeometry(QRect(170, 80, 81, 20))
        self.label.setObjectName("label")
        self.open_file_button = QPushButton(Dialog)
        self.open_file_button.setGeometry(QRect(30, 120, 191, 31))
        self.open_file_button.setParent(Dialog)
        self.open_file_button.setObjectName("open_file_button")
        self.open_file_button.clicked.connect(self.handleOpenFileButtonClick)
        self.lineEdit = QLineEdit(Dialog)
        self.lineEdit.setGeometry(QRect(220, 125, 300, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QRect(220, 155, 300, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.set_save_file_button = QPushButton(Dialog)
        self.set_save_file_button.setGeometry(QRect(50, 150, 171, 31))
        self.set_save_file_button.setObjectName("set_save_file_button")
        self.set_save_file_button.clicked.connect(self.handleSaveFileButtonClick)
        self.run_program_button = QPushButton(Dialog)
        self.run_program_button.setGeometry(QRect(220, 190, 144, 32))
        self.run_program_button.setObjectName("run_program_button")
        self.run_program_button.clicked.connect(self.runProgram)
        self.run_program_button.setDisabled(True)

        # Set up default file parameters
        self.original_filename = self.default_open_path
        self.lineEdit.setText(self.original_filename)
        if self.original_filename:
            self.open_file_found = True
        self.new_save_filename = self.default_save_path
        self.lineEdit_2.setText(self.new_save_filename)
        if self.new_save_filename:
            self.save_file_found = True

        if self.open_file_found and self.save_file_found:
            self.run_program_button.setDisabled(False)
        else:
            self.run_program_button.setDisabled(True)

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)
        self.show()

    def temp_retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        self.label.setText(_translate("Dialog", "Select a Day:"))
        self.open_file_button.setText(_translate("Dialog", "Choose Original Filename:"))
        self.set_save_file_button.setText(_translate("Dialog", "Choose New Filename:"))
        self.run_program_button.setText(_translate("Dialog", "Set Up Schedule"))

    def runProgram(self):
        self.day_index = self.day_selector.currentIndex()

        # Setup and copy workbook.
        book = xlrd.open_workbook(filename=self.original_filename, formatting_info=True, on_demand=True)
        new_schedule = copy(book)

        hour_ce_counts = [self.eight_am_ce_count.currentIndex(), self.nine_am_ce_count.currentIndex(), self.ten_am_ce_count.currentIndex(),
                          self.eleven_am_ce_count.currentIndex(), self.twelve_pm_ce_count.currentIndex(), self.one_pm_ce_count.currentIndex(),
                          self.two_pm_ce_count.currentIndex(), self.three_pm_ce_count.currentIndex(), self.four_pm_ce_count.currentIndex(),
                          self.five_pm_ce_count.currentIndex(), self.six_pm_ce_count.currentIndex(), self.seven_pm_ce_count.currentIndex(),
                          self.eight_pm_ce_count.currentIndex()]

        excelWriter = ExcelWriter(book, new_schedule.get_sheet(self.day_index + 3),
                                  book.sheet_by_index(self.day_index + 3),
                                  new_schedule,
                                  Styles(book), self.new_save_filename, hour_ce_counts)

        # Set break and lunch times in new excel file.
        excelWriter.calcBreakTimes()
        excelWriter.calcLunchTimes()

        # Set up schedule (Color Cells)
        excelWriter.colorCells()

        # This only used for original presentation purposes.
        #excelWriter.test_colorCells()

        # Open editing table.
        ex = VisualTable(self.new_save_filename, excelWriter.calcNumEmployees(), self.day_index)
        ex.createTable()

        # Close opening main window.
        self.close()

    def handleOpenFileButtonClick(self):
        file_dialog = QFileDialog()
        file_dialog.move(300, 300)
        options = file_dialog.Options()
        options |= file_dialog.DontUseNativeDialog

        self.original_filename, _ = file_dialog.getOpenFileName(self, "Choose a schedule", self.default_open_path, "Excel Files (*.xls)", options=options)
        if self.original_filename:
            self.open_file_found = True
            self.lineEdit.setText(self.original_filename)
        else:
            self.open_file_found = False

        if self.open_file_found and self.save_file_found:
            self.run_program_button.setDisabled(False)
        else:
            self.run_program_button.setDisabled(True)

    def handleSaveFileButtonClick(self):
        file_dialog = QFileDialog()
        file_dialog.move(300,300)
        options = file_dialog.Options()
        options |= file_dialog.DontUseNativeDialog

        self.new_save_filename, _ = file_dialog.getSaveFileName(self, "Choose new filename", self.default_save_path, "Excel Files (*.xls)", options= options)
        if self.new_save_filename[-4:] != ".xls":
            self.new_save_filename = self.new_save_filename + ".xls"

        if self.new_save_filename != ".xls":
            self.save_file_found = True
            self.lineEdit_2.setText(self.new_save_filename)
        else:
            self.save_file_found = False

        if self.open_file_found and self.save_file_found:
            self.run_program_button.setDisabled(False)
        else:
            self.run_program_button.setDisabled(True)

    def handleDayIndexChanged(self, index):
        self.day_index = index